spring.datasource.url=jdbc:mysql://localhost:3306/loan?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=@Zhangzhe0090155
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.address=0.0.0.0
server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
#spring.data.redis.password=@Zhangzhe0090155
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-wait=-1ms
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=1152974119@qq.com
spring.mail.password=qrzmqeiwakuebaae
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

dashscope.api.key=sk-9752397cce4e4386b26af9ad9c6619e5
dashscope.crawler.app.id=6d45d27afe25445b9dd16e4ca2407f9c

langchain4j.open-ai.chat-model.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
langchain4j.open-ai.chat-model.model-name=qwen-plus
langchain4j.open-ai.chat-model.api-key=sk-9752397cce4e4386b26af9ad9c6619e5
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

langchain4j.open-ai.streaming-chat-model.api-key=sk-9752397cce4e4386b26af9ad9c6619e5
langchain4j.open-ai.streaming-chat-model.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
langchain4j.open-ai.streaming-chat-model.model-name=qwen-plus
langchain4j.open-ai.streaming-chat-model.log-requests=true
langchain4j.open-ai.streaming-chat-model.log-responses=true